### ISSUE TITLE
[Documentation] Extraction Column showing text for CSTR

### ISSUE THREAD

**Issue by GermanHeim** [MaximilianB2/pc-gym#25]
Hello,

The Description & Equation sections for the docs of the [Extraction Column](https://maximilianb2.github.io/pc-gym/env/extraction-column/) shows text from the CSTR env in the first paragraph.

It should be easy to change from the [markdown file](https://github.com/MaximilianB2/pc-gym/blob/main/docs/env/extraction-column.md).

**Comment by GermanHeim** [comment]
Also, the image isn't showing since the file starts with a capital M and E (multistage_extractor.png should be Multistage_Extractor.png). The same happens with the CSTR image.

**Comment by MaximilianB2** [comment]
Hi German, 

Thanks for spotting these issues. I have committed a fix to the documentation as you suggested.
